const actionTypes = {
    THEME_CHANGE_DIRECTION: 'THEME_CHANGE_DIRECTION',
    THEME_CHANGE_PALETTE_COLORS: 'THEME_CHANGE_PALETTE_COLORS',
    THEME_CHANGE_PALETTE_TYPE: 'THEME_CHANGE_PALETTE_TYPE',
  };
 
export const FETCH_FORM_STRUCT = 'FETCH_FORM_STRUCT';
export default actionTypes;
